_format_version: "3.0"
services:
  - name: auth-service
    url: http://auth-service:5000
    routes:
      - name: auth-routes
        strip_path: false
        paths:
          - /auth
  - name: institute-service
    url: http://institute-service:5000
    routes:
      - name: institute-routes
        strip_path: false
        paths:
          - /institutes
          - /semesters
          - /degrees
          - /classes
          - /courses
          - /submission-api
  - name: user-service
    url: http://user-service:5000
    routes:
      - name: user-routes
        strip_path: false
        paths:
          - /users
  - name: ivas-service
    url: http://ivas-service:8084
    routes:
      - name: ivas-routes
        strip_path: false
        paths:
          - /api/v1/viva
  - name: keystroke-service
    url: http://keystroke-ml-service:8003
    routes:
      - name: keystroke-routes
        strip_path: false
        paths:
          - /api/keystroke
plugins:
  - name: cors
    config:
      origins:
        - "http://localhost:3000"
        - "http://localhost:3001"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
        - HEAD
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      preflight_continue: false
